### ISSUE TITLE
Comparison with other dprime methods

### ISSUE THREAD

**Issue by DominiqueMakowski** [sam81/DetectionTheory.jl#4]
Dear @sam81, 

I recently started working on the adaptation of the [`psycho`](https://github.com/neuropsychology/psycho.R) package for R to [Julia](https://github.com/neuropsychology/Psycho.jl) and, as a way of learning the language, started implementing some fairly basic functions related to SDT. Curiously, I just discovered your great package. However, your dprime function (`dprimeABX()`) returns different results compared to the basic dprime traditional method that I implemented [here](https://github.com/neuropsychology/Psycho.jl/blob/master/src/sdt/basics.jl#L28). 

```julia
using Psycho, DetectionTheory

dprimeABX(0.7, 0.3, "diff")
> 1.715301562311248
dprimeABX(0.7, 0.3, "IO")
> 1.5286932848434585
sdt_indices(7, 3, 3, 7)["dprime"]
> 0.903132472060801
sdt_indices(7, 3, 3, 7, adjusted=false)["dprime"]
> 1.0488010254160816
```
Could you enlighten me on the reasons of this discrepancy? 😃
Thanks

**Comment by sam81** [comment]
`dprimeABX` in `DetectionTheory` computes d' for the ABX task, while the function you implemented in `Psycho` computes d' for the classical Yes/No detection task.   
If you use the corresponding function for the Yes/No task in `DetectionTheory` the results match:

    dprimeYesNo(0.7, 0.3)
    > 1.0488010254160813

The information available to the observer in the ABX task is different from that available in the Yes/No task (e.g. in the ABX task the observer is presented on each trial with three stimuli rather than one), and although the underlying principles for computing d' are the same, the models are different. Two models have been proposed for the ABX task, the differencing model, and the independent observations model, hence there are two ways to compute d' for the ABX task. The following references cover the SDT models for the ABX task:

Hautus, M. J., & Meng, X. (2002). Decision strategies in the ABX (matching-to-sample) psychophysical task. Perception & Psychophysics, 64(1), 89–106.
Kingdom, F. A. A., & Prins, N. (2010). Psychophysics: A Practical Introduction. Academic Press.
Macmillan, N. A., Kaplan, H. L., & Creelman, C. D. (1977). The psychophysics of categorical perception. Psychological Review, 84(5), 452–471.
Macmillan, Neil A., & Creelman, C. D. (2004). Detection Theory: A User’s Guide (2nd ed.). London: Lawrence Erlbraum Associates.
Noreen, D. L. (1981). Optimal decision rules for some common psychophysical paradigms. In S. Grossberg (Ed.), Mathematical psychology and psychophysiology. Proceedings of the Symposium in Applied Mathematics of the American Mathematical Society and the Society for Industrial and Applied Mathematics (Vol. 13, pp. 237–279). Providence, RI: American Mathematical Society.

**Comment by DominiqueMakowski** [comment]
Seems like I overlooked the meaning of ABX, thanks for this comprehensive answer!
